import { useEffect, useState } from "react";
import { Link } from "wouter";

const target = new Date("2026-11-14T09:00:00+05:30").getTime();
function useCountdown() { const [left, setLeft] = useState(target - Date.now()); useEffect(() => { const id = setInterval(() => setLeft(Math.max(0, target - Date.now())), 1000); return () => clearInterval(id); }, []); const d = Math.floor(left / 86400000); const h = Math.floor((left % 86400000) / 3600000); const m = Math.floor((left % 3600000) / 60000); const s = Math.floor((left % 60000) / 1000); return [d,h,m,s].map(x => String(x).padStart(2,"0")).join(" : "); }
const events = [["01","⌘","Hack the grid","Ship a working product before the clock ships you."],["02","⚙","Robo riot","Steel, sensors and a little controlled chaos."],["03","▣","Red CTF","Find the flaw. Take the flag. Leave no trace."]];
export default function Home() { const countdown = useCountdown(); return <>
  <section className="hero"><div className="hero-noise" /><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow cream">Annual college tech fest // Edition 08</div><h1>RE<span>/</span>LINE</h1><p className="hero-lede">A high-voltage collision of code, circuits, ideas and the people reckless enough to build the future.</p><div className="tag-row"><span>14—15 NOV 2026</span><span>NEXUS CAMPUS / PUNE</span></div><div className="button-row"><Link className="button button-red clip" href="/register">Enter the arena ↗</Link><Link className="button button-outline cream clip" href="/events">Explore events ↓</Link></div></div><div className="countdown"><small>System ignition in</small><strong>{countdown}</strong></div></div></section>
  <section className="section"><div className="container section-head"><div><div className="eyebrow">01 // The brief</div><h2>Make<br /><em>noise.</em></h2></div><p className="section-note">A two-day collision of builders, breakers and bright ideas. Placeholder copy — swap in your official fest story when ready.</p></div><div className="container intro-grid"><p className="intro-statement">REDLINE is where <em>sharp minds</em> meet hard problems. No spectators. Just a live wire of people building the future.</p><div className="stat-grid"><div><b>36</b><span>Hours of mayhem</span></div><div><b>06</b><span>Tracks to conquer</span></div><div><b>2.5K</b><span>Participants</span></div><div><b>₹8L</b><span>Prize pool</span></div></div></div></section>
  <section className="section dark-section"><div className="container section-head"><div><div className="eyebrow muted">02 // Pick your weapon</div><h2>Six ways<br />to <em>break</em> it.</h2></div><Link className="text-link" href="/events">View all events ↗</Link></div><div className="container event-grid">{events.map(([num,icon,title,text]) => <article className="event-card" key={num}><span className="event-num">{num}</span><span className="event-icon">{icon}</span><h3>{title}</h3><p>{text}</p><Link href="/events">Explore track ↗</Link></article>)}</div></section>
  <section className="red-cta"><div className="container cta-inner"><div><div className="eyebrow">03 // Your move</div><h2>Cross<br />the line.</h2></div><div><p>Registration is open for the next wave of makers, hackers and troublemakers.</p><Link className="button button-ink clip" href="/register">Register your crew ↗</Link></div></div></section>
</>; }
